Job success status

diff --git a/cloud/corfu/corfu/templates/job.yaml b/cloud/corfu/corfu/templates/job.yaml
--- a/cloud/corfu/corfu/templates/job.yaml
+++ b/cloud/corfu/corfu/templates/job.yaml
@@ -8,119 +8,114 @@ spec:
   template:
     spec:
       {{- if .Values.imagePullSecretsEnabled }}
-      {{- with .Values.imagePullSecrets }}
-      imagePullSecrets:
-        {{- toYaml . | nindent 8 }}
-      {{- end }}
-      {{- end }}
-      restartPolicy: OnFailure
-      {{- if .Values.serviceAccount.create }}
-      serviceAccountName: {{ include "corfu.serviceAccountName" . }}
-      {{- end }}
-      securityContext:
-        {{- toYaml .Values.podSecurityContext | nindent 8 }}
-      initContainers:
-        - name: create-layout
-          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
-          imagePullPolicy: {{ .Values.image.pullPolicy }}
-          command:
-            - "/bin/bash"
-            - "-c"
-            - |
-              set -e
-              python3 /etc/corfu/configs/init_layout.py --template /etc/corfu/configs/layout_template.json --layout /usr/share/configs/layout.json \
-                --replica {{ include "corfu.replicas" . }} --statefulset {{ include "corfu.name" . }} --headless {{ include "corfu.name" . }}-headless --port {{ .Values.service.port }}
-          env:
-            - name: POD_NAMESPACE
-              valueFrom:
-                fieldRef:
-                  fieldPath: metadata.namespace
-          volumeMounts:
-            - name: workdir
-              mountPath: /usr/share/configs
-            - name: corfu-layout-configs
-              mountPath: /etc/corfu/configs
-      containers:
-        - name: bootstrap-corfu
-          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
-          imagePullPolicy: {{ .Values.image.pullPolicy }}
-          command:
-            - "/bin/bash"
-            - "-c"
-            - |
-              set -e
+        {{- with .Values.imagePullSecrets }}
+        imagePullSecrets:
+          {{- toYaml . | nindent 8 }}
+        {{- end }}
+        {{- end }}
+        restartPolicy: OnFailure
+        {{- if .Values.serviceAccount.create }}
+        serviceAccountName: {{ include "corfu.serviceAccountName" . }}
+        {{- end }}
+        securityContext:
+          {{- toYaml .Values.podSecurityContext | nindent 8 }}
+        initContainers:
+          - name: create-layout
+            image: {{ include "imageSpec" ( dict "image" .Values.images.corfu  "global" .Values.global) }}
+            imagePullPolicy: {{ .Values.images.corfu.pullPolicy }}
+            command:
+              - "/bin/bash"
+              - "-c"
+              - |
+                set -e
+                python3 /etc/corfu/configs/init_layout.py --template /etc/corfu/configs/layout_template.json --layout /usr/share/configs/layout.json \
+                  --replica {{ include "corfu.replicas" . }} --statefulset {{ include "corfu.name" . }} --headless {{ include "corfu.name" . }}-headless --port {{ .Values.service.port }}
+            env:
+              - name: POD_NAMESPACE
+                valueFrom:
+                  fieldRef:
+                    fieldPath: metadata.namespace
+            volumeMounts:
+              - name: workdir
+                mountPath: /usr/share/configs
+              - name: corfu-layout-configs
+                mountPath: /etc/corfu/configs
+        containers:
+          - name: bootstrap-corfu
+            image: {{ include "imageSpec" ( dict "image" .Values.images.corfu  "global" .Values.global) }}
+            imagePullPolicy: {{ .Values.images.corfu.pullPolicy }}
+            command:
+              - "/bin/bash"
+              - "-c"
+              - |
+                set -e
 
-              {{- if .Values.tls.enabled }}
-              certs_truststore_file=/certs/truststore.jks
-              if test -f "$certs_truststore_file";
-              then
-                echo "$certs_truststore_file mounted sucessfully."
-              else
-                echo "ERROR: $certs_truststore_file NOT mounted!"
+                {{- if .Values.tls.enabled }}
+                certs_truststore_file=/certs/truststore.jks
+                if test -f "$certs_truststore_file";
+                then
+                  echo "$certs_truststore_file mounted sucessfully."
+                else
+                  echo "ERROR: $certs_truststore_file NOT mounted!"
+                  exit 1
+                fi
+                {{- end }}
+
+                /usr/share/corfu/bin/corfu_ping \
+                {{- if .Values.tls.enabled }}
+                --enable-tls --keystore=/certs/keystore.jks  --truststore=/certs/truststore.jks \
+                --keystore-password-file=/password/password --truststore-password-file=/password/password \
+                {{- end }}
+                 --retries 10 --timeout 5000 $(cat /configs/layout.json | jq -r '.layoutServers | join(" ")') \
+                 &> /tmp/ping.log
+
+                if grep -q "All nodes are reachable!" "/tmp/ping.log"; then
+                  echo "All nodes are reachable!"
+                else
+                  cat /tmp/ping.log
+                  exit 1
+                fi
+
+                echo "bootstrap cluster with layout:"
+                cat /configs/layout.json
+                echo
+
+                /usr/share/corfu/bin/corfu_bootstrap_cluster --layout=/configs/layout.json \
+                --connection-timeout 2000 \
+                {{- if .Values.tls.enabled }}
+                --enable-tls --keystore=/certs/keystore.jks  --truststore=/certs/truststore.jks \
+                --keystore-password-file=/password/password --truststore-password-file=/password/password \
+                {{- end }}
+                &> /tmp/bootstrap.log
+
+                if grep -q "New layout installed successfully!" "/tmp/bootstrap.log"; then
+                  echo "Above layout was installed successfully!"
+                  exit 0
+                fi
+
+                echo "Bootstrap has failed with an error"
+                cat /tmp/bootstrap.log
                 exit 1
-              fi
-              {{- end }}
-
-              /usr/share/corfu/bin/corfu_ping \
+            volumeMounts:
+              - name: workdir
+                mountPath: /configs
               {{- if .Values.tls.enabled }}
-              --enable-tls --keystore=/certs/keystore.jks  --truststore=/certs/truststore.jks \
-              --keystore-password-file=/password/password --truststore-password-file=/password/password \
+              - name: certificate
+                mountPath: /certs
+              - name: password
+                mountPath: /password
               {{- end }}
-               --retries 10 --timeout 5000 $(cat /configs/layout.json | jq -r '.layoutServers | join(" ")') \
-               &> /tmp/ping.log
-
-              if grep -q "All nodes are reachable!" "/tmp/ping.log"; then
-                echo "All nodes are reachable!"
-              else
-                cat /tmp/ping.log
-                exit 1
-              fi
-
-              echo "bootstrap cluster with layout:"
-              cat /configs/layout.json
-              echo
-
-              /usr/share/corfu/bin/corfu_bootstrap_cluster --layout=/configs/layout.json \
-              --connection-timeout 2000 \
-              {{- if .Values.tls.enabled }}
-              --enable-tls --keystore=/certs/keystore.jks  --truststore=/certs/truststore.jks \
-              --keystore-password-file=/password/password --truststore-password-file=/password/password \
-              {{- end }}
-              &> /tmp/bootstrap.log
-
-              if grep -q "New layout installed!" "/tmp/bootstrap.log"; then
-                echo "Above layout was installed successfully!"
-                exit 0
-              fi
-
-              if grep -q "Server is already bootstrapped" "/tmp/bootstrap.log"; then
-                echo "The servers are already bootstrapped"
-                exit 0
-              fi
-
-              echo "Bootstrap has failed with an error"
-              cat /tmp/bootstrap.log
-              exit 1
-          volumeMounts:
-            - name: workdir
-              mountPath: /configs
-            {{- if .Values.tls.enabled }}
-            - name: certificate
-              mountPath: /certs
-            - name: password
-              mountPath: /password
-            {{- end }}
-      volumes:
-        - name: workdir
-          emptyDir: {}
-        - name: {{ include "corfu.fullname" . }}-layout-configs
-          configMap:
-            name: {{ include "corfu.fullname" . }}-layout-configs
-        {{- if .Values.tls.enabled }}
-        - name: certificate
+        volumes:
+          - name: workdir
+            emptyDir: {}
+          - name: {{ include "corfu.fullname" . }}-layout-configs
+            configMap:
+              name: {{ include "corfu.fullname" . }}-layout-configs
+          {{- if .Values.tls.enabled }}
+          - name: certificate
           secret:
             secretName: {{ .Values.tls.secretName }}
-        - name: password
-          secret:
-            secretName: {{ .Values.tls.passwordName }}
-        {{- end }}
+          - name: password
+            secret:
+              secretName: {{ .Values.tls.passwordName }}
+          {{- end }}
